### ISSUE TITLE
Where can I find the source for the ALADYMTools package?

### ISSUE THREAD

**Issue by gustavdelius** [Isabella84/BEMTOOL2.5#1]
There is a windows binary for the package in this repository, but I would like to find the source so I can install it under Linux.

**Comment by Isabella84** [comment]
I put the source package in the BEMTOOL 2.5 folder. Let me know if it is fine.

**Comment by gustavdelius** [comment]
Thanks, that worked well.

**Comment by gustavdelius** [comment]
I assume there is no other home for the ALADYMTools package? If there is another home, then perhaps BEMTOOL should link to it rather than containing a copy.
